### ISSUE TITLE
优雅的修改他人贡献的 Pull Request

### ISSUE THREAD

**Issue by cjh0613** [liuyib/liuyib.github.io#34]
直接用万能的 github.com 在线修改，支持手机

另外，`https://liuyib.github.io/2020/09/19/add-commits-to-others-pr/` 的评论，……

**Comment by liuyib** [comment]
> 直接用万能的 github.com 在线修改，支持手机
> 
> 另外，`https://liuyib.github.io/2020/09/19/add-commits-to-others-pr/` 的评论，……

回头试试在线修改。

Disqus 国内没法用 😂，过段时间换成 DisqusJS

**Comment by liuyib** [comment]
@cjh0613

尝试了github 的在线修改pr，一次只能修改一个文件，不太好用 😂

**Comment by cjh0613** [comment]
Github 正在开发在线 IDE 工具——Codespaces，目前已向公众开放小规模测试，值得关注
